language: cpp
compiler:
  - gcc
  - clang
sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6

script:
      - mkdir build
      - cd build
      - cmake .. && make

notifications:
  email: false
